# Dockerfile for Flask app
FROM python:3.9
WORKDIR /app
COPY . /app
# should pin to a specific version of dependencies later - to avoid breaking changes.
# for now, just install the latest version.
RUN pip install Flask
RUN pip install Flask-Cors
RUN pip install psycopg2
CMD ["python", "app.py"]
